### ISSUE TITLE
Responder e-mails, mensagens de pessoas interessadas pelo projeto

### ISSUE THREAD

**Issue by sahrosa** [design-na-escola/projeto#1]

**Comment by sahrosa** [comment]
- [x] Vinicius costa (messenger)
- [x] Felipe Barcelos (email)
- [x] Pedro beleza - colaborador
- [x] Lígia Medeiros (email)
- [x] Karina moura (escola palestra)
- [x] Barbara tubelo - colaborador
- [x] Adriane Lemos - colaborador
- [x] Jorge rosa - colaborador
- [x] Kamila kunrath - colaborador
- [x] Ana Pedersen - colaborador
- [x] Alisson Douglas - (email)
- [x] Jane Rosa - colaborador
- [x] Thiago Esser - colaborador
- [x] Raquel Sordi - colaborador
- [x] Badika Padilha - parceiro (messenger)
- [x] Mara Hermes - colaborador (Messenger)
- [x] Carolina Novais - colaborador (Messenger)
- [x] Soraya Pamplona - interessada (email)
- [x] Karuan Bertoluci - colaborador (email)
- [x] Rodrigo Martins - colaborador (email)
- [x] César alcon - colaborador (email)
- [x] Alex suliano - interessado (email)
- [x] Elenice Lopes - colaborador (email)
- [x] Moisés ribeiro - possível parceiro (irmã) (email)
- [x] Alisson Laschuk - colaborador (email)
- [x] Fernanda marques - colaborador
- [x] Eric gornicki Vargas - colaborador
- [x] Lucas oliveira - interessado 
- [x] Bruno Lorenz - interessado 
- [x] Iuri Moreira - parceiro
- [x] Társis azevedo - parceiro dsv (medium) 
- [x] Thiago tomassi - colaborador  
- [x] Raissa Esther - colaborador 
- [x] Quitéria Oliveira - Esta nos rascunhos para resposta
- [x] Vereda criativa - Sah
- [x] Alice Meditsch - Esta nos rascunho para resposta
- [x] Jaqueline Piccini  - Esta nos rascunho para resposta
- [x] Ivna Ravanello - Email 
- [x] Angelica Oliveiria

**Comment by rafaelweiblen** [comment]
@sahrosa 

Respondi os e-mail que estavam na caixa de entrada do designontheroad.
Respondi também para os outros que não estavam no e-mail, mas eu tinha o contato.
Os novos e-mail deixei um rascunho para tu olhar.
