### ISSUE TITLE
Post no facebook procurando pessoas

### ISSUE THREAD

**Issue by rafaelweiblen** [design-na-escola/projeto#16]

**Comment by sahrosa** [comment]
Vamos enviar até terça-feira

**Comment by sahrosa** [comment]
Decidimos esperar a confirmação do local

**Comment by sahrosa** [comment]
Utilizar o form: https://docs.google.com/forms/d/12QmqIs-zqI5bpjUbxZOFR5scCNEVjoWDcMxIVYISY7o/viewform
