### ISSUE TITLE
Criar checklist do que precisa ser falado durante cada curso

### ISSUE THREAD

**Issue by sahrosa** [design-na-escola/projeto#20]
- [ ] Repassar materiais da IDEO
- [ ] Revisar links sobre design para educadores

**Comment by rafaelweiblen** [comment]
### Mini curso e os conceitos por trás das técnicas:

**Entrevista:** Criar empatia e mostrar os problemas pelo ponto de vista de outra pessoa
**Brainstorming:** Trabalhar de forma colaborativa para gerar uma solução 
**Prototipação:** Nós podemos criar soluções simples e viáveis e testá-las rapidamente
**Processo:** Todo mundo pode ser designer e criar soluções de forma ágil. 

### Curso completo e os conceitos por trás das técnicas:

**Visão do produto:** Forma de criar um visão única para todos e criar  foco ajudando a tornar um problema menor e conseguir criar soluções. 
**Personas:** Empatia com as pessoas é fundamental para criar soluções relevantes para seu público.
**Objetivos:** Criatividade e foco em soluções significativas.
**Mapa de experiência:** Análise de contexto ajuda a enxergar o todo e encontrar pontos de ação.
**Descobrindo funcionalidades:** Trabalhar de forma colaborativa para gerar um solução.
**Avaliar:** Foco e prioridade é fundamental para tornar o projeto viável e de uma forma rápida para implementar.
**Processo:** Todo mundo pode ser designer e criar soluções de forma ágil.

**Comment by rafaelweiblen** [comment]
ó @sahrosa avalia
