### ISSUE TITLE
Formulário inicial de curso

### ISSUE THREAD

**Issue by sahrosa** [design-na-escola/projeto#21]

**Comment by rafaelweiblen** [comment]
Com base em sua experiência durante este mini curso, o design centrado nas pessoas pode ser útil no seu dia a dia? como?

Quais ensinamentos do design centrado nas pessoas você gostou e levaria como técnica para resolver as dificuldades do seu dia a dia?

**Comment by sahrosa** [comment]
- O que você acha que vai aprender com este curso?
- Por onde que você conheceu o curso?
