### ISSUE TITLE
Criar documento de é/não/faz/não faz no git

### ISSUE THREAD

**Issue by sahrosa** [design-na-escola/projeto#24]

**Comment by sahrosa** [comment]
Documento disponível aqui por enquanto: https://docs.google.com/spreadsheets/d/1jxURSZqXWqRIcCkZ5fIdj5L7DUEuJkV7p0GjgAxBNlo/edit?usp=sharing

**Comment by tarsisazevedo** [comment]
Poderia ser criada uma pagina na wiki do projeto, ou adicionar essas infos no README do projeto (eu acho melhor).

Se a pagina na wiki for criada, ela poderia ser linkada no README para quem chegar aqui saber já de cara o que é e nao é.

**Comment by sahrosa** [comment]
Ótima ideia @tarsisazevedo!!!
