### ISSUE TITLE
Apresentação N Design

### ISSUE THREAD

**Issue by sahrosa** [design-na-escola/projeto#28]
Montar o roteiro e a estrutura da apresentação

**Comment by sahrosa** [comment]
Descobrir de quanto tempo será a apresentação.

**Comment by sahrosa** [comment]
Começando neste documento: https://github.com/design-na-escola/projeto/commit/cd028d2877965ef508ff7e0c6bfce85ac021da92

**Comment by rafaelweiblen** [comment]
Arco baixo 
- Cenário atual do brasil 
- Não consigo ser aquilo que não me vejo 

Arco alto 
- Isto motivou o projeto  
- O design tem responsabilidade e é preciso devolver para a sociedade 

Arco baixo 
- Dados do N design 

Arco alto 
- Proposta:  estudar (leituras semanais), praticar (colocar a mão na massa) e discutir (aprender a pensar, gerar a conversa e não apenas seguir instruções).
- Design centrado nas pessoas 

Arco alto 
- Experimentos 
- Resultados 
- Feedback 
- Roadmap

**Comment by sahrosa** [comment]
Olhar o cartão #33 para complementar os dados raciais.
