### ISSUE TITLE
Roadmap do projeto

### ISSUE THREAD

**Issue by tarsisazevedo** [design-na-escola/projeto#30]
Acompanho o projeto de vocês de longe, e acho a ideia muito irada! :clap: :clap: :clap: 
Para deixar o trabalho mais claro e trazer mais gente pra ajudar acho que seria legal tem um Roadmap do projeto.

Nesse roadmap teriam os objetivos de curto prazo e longo prazo, assim como as ações que vocês ja estão tomando.

Hoje trabalho num projeto open source (tsuru) e lá temos um roadmap, para que os colaboradores e usuarios do projeto saibam pra onde estamos indo (https://github.com/tsuru/tsuru/blob/master/docs/roadmap.rst).

Essas informações poderiam estar no readme, por enquanto.

**Comment by rafaelweiblen** [comment]
Bahh muito boa a ideia

Em seg, 15 de jun de 2015 às 23:38, Tarsis Azevedo notifications@github.com
escreveu:
