### ISSUE TITLE
Entende convexo

### ISSUE THREAD

**Issue by rafaelweiblen** [design-na-escola/projeto#44]

**Comment by rafaelweiblen** [comment]
Estou falando com a Betina para combinar uma data

**Comment by sahrosa** [comment]
- Eles já tem uma pegada bem empreendedora e empiricamente fazem muito design thinking. 
- São uma boa referência de como fazer as coisas de forma diferente.
- Alunos criaram um negócio na vila em que moram, junto a um restaurante e vão fazer óleo aromatizado.
