### ISSUE TITLE
Estrutura do curso

### ISSUE THREAD

**Issue by thiagotomasi** [design-na-escola/projeto#51]
@sahrosa e @rafaelweiblen nas minha pesquisas sobre UX e cursos sobre UX acabei de chegando nestes links:
- https://github.com/fehler/curriculum
- http://ixdbelfast.org/curriculum/

É a ideia desse projeto é de uma graduação em Design de Interação com a ementa toda `open source` e livre para a colaboração. Não sei se a ideia saiu do papel, mas acredito que o projeto `design na escola` poderia se tornar algo assim.

Um curso completamente free, com modulos, materiais de apoio e até projeto para avaliação quem sabe. Sei a ideia é meio grandiosa, mas me veio hoje na cabeça e gostaria de saber o que vocês acham?

Outros exemplos são:
- https://github.com/FreeCodeCamp/FreeCodeCamp
- http://plusacumen.org/courses/hcd-for-social-innovation/

Mas acredito que a o diferencial seria ser um curso bem completo, desde os conceitos básicos até tópicos mais avançados.

**Comment by rafaelweiblen** [comment]
to até com vergonha de responder depois de mais um ano @thiagotomasi 

Tivemos grandes mudanças no nosso dia a dia e acabamos parando o projeto, vamos retomar agora e teus inputs vão nos ajudar bastante. 

Sobre a tua pergunta, eu sou uma pessoa que adora baixar a complexidade ao mínimo essencial para conseguir colocar em produção :)

Acredito que com a prática a ideia pode ir incrementando e se tornar algo mais próximo do que tu comentou, o que acha?
